[package]
authors = ["konstin <konstin@mailbox.org>"]
name = "pyo3-no-extension-module"
version = "2.1.0"
description = "Does not use the extension-module feature, thus errorneously linking libpython"
edition = "2018"

[dependencies]
pyo3 = { version = "0.13.2", default-features = false }

[lib]
name = "pyo3_no_extension_module"
crate-type = ["cdylib"]
